#!/usr/bin/env python

import pywbxml
from util import *
from xml.dom import minidom

raw_xml = r"""<?xml version="1.0" ?><!DOCTYPE AirSync PUBLIC "-//AIRSYNC//DTD AirSync//EN" "http://www.microsoft.com/"><FolderSync><SyncKey>0</SyncKey></FolderSync>
"""
doc = minidom.parseString(raw_xml)
print "Input (pretty-printed):"
print doc.toprettyxml()

wbxml = pywbxml.xml2wbxml(raw_xml)

print "Produced:"
print hexdump(wbxml)

expected = "\x03\x01\x6a\x00\x00\x07\x56\x52\x03\x30\x00\x01\x01"
print "Expected:"
print hexdump(expected)

